# serverless.yml

service: redditscoreml

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-2
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "s3:*"
  #     Resource:
  #         - "*"

functions:
  app:
    handler: wsgi.handler
    events:
      - http:
          path: predict
          method: post
          cors: true
      # - http: ANY /
      # - http: 'ANY {proxy+}'